image: Visual Studio 2017
$msbuildPath = $(cmd /c "%programfiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\MsBuild.exe")

install:
  - ps: Install-Package xunit -Force -Confirm:$true

init:
  - git config --global core.autocrlf true
shallow_clone: true 

before_build:
  - appveyor-retry dotnet restore
test: on
test_script:
  - ps: .\run-tests.ps1
deploy: off
